# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 4  # number of gpus each job need
num_cpus_per_job: 8  # number of cpus each job need
memory_per_job: 380  # memory requirement each job need
gpu_type: "nvidia-geforce-gtx-1080"

# data
dataset: imagenet1k
data_transforms: imagenet1k_basic
data_loader: imagenet1k_basic
dataset_dir: ../../Datasets/IMAGENET/ImageNet_smallSize256
data_loader_workers: 8

# info
topk: [1]
num_epochs: 100

# optimizer
optimizer: adam
momentum: 0.9
weight_decay: 0.0001
nesterov: True

# lr
lr: 0.0005
lr_scheduler: multistep
multistep_lr_milestones: [20, 30, 40]
multistep_lr_gamma: 0.1

# model profiling
profiling: [gpu]

# pretrain, resume, test_only
pretrained: ''
resume: ''
test_only: False

#
random_seed: 1995
batch_size: 128
model: ''
reset_parameters: True

# =========================== Override Settings ===========================
log_dir: logs/
slimmable_training: True
model: models.s_resnet
depth: 18
width_mult: 1.0
width_mult_list: [1.0]
bitwidth_list: [32]
bitactiv_list: [2]
num_gpus_per_job: 1
# test pretrained
#test_only: True
pretrained: logs/best_model_imagenet1k_models.s_resnet18_1.0__6464.pt
